server:
  port: 8090
spring:
  ai:
#    openai:
#      qwen-flash:
#        api-key: ${API-KEY}
#        base-url: https://dashscope.aliyuncs.com/compatible-mode
#        chat:
#          options:
#            model: qwen-flash
#            #这个参数越小，模型回答越固定
#            temperature: 0.5
    openai:
      api-key: ${ALIBABAA-API-KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: glm-4.7
          #这个参数越小，模型回答越固定
          temperature: 0.5
    zhipuai:
      api-key: ${ZHIPU-API-KEY}
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
          temperature: 0.7